<a href="https://colab.research.google.com/github/SahilRaut80/Assignments/blob/main/basics_stats_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
import numpy as np

In [45]:
df = pd.read_csv('Patient_Data.csv')
df2 = pd.read_csv('Billing_Data.csv')

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [47]:
df[['PatientID','Department','BillAmount','Doctor']]

   PatientID   Department  BillAmount     Doctor
0        101   Cardiology      5000.0  Dr. Smith
1        102    Neurology         NaN   Dr. John
2        103  Orthopedics      7500.0    Dr. Lee
3        104   Cardiology      6200.0  Dr. Smith
4        105  Dermatology         NaN   Dr. Rose
5        101   Cardiology      5000.0  Dr. Smith

In [48]:
df = df.drop(columns= ['ReceptionistID', 'CheckInTime'])
df

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

In [49]:
df.groupby('Department')['BillAmount'].sum()

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

In [50]:
df.duplicated().sum()

np.int64(1)

In [51]:
df.drop_duplicates(inplace=True)

In [52]:
df.duplicated().sum()

np.int64(0)

In [54]:
df.isnull().sum()

PatientID     0
Name          0
Department    0
Doctor        0
BillAmount    2
dtype: int64

In [55]:
df['BillAmount'].fillna(df['BillAmount'].mean(), inplace=True)

/tmp/ipykernel_1680/302196808.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BillAmount'].fillna(df['BillAmount'].mean(), inplace=True)

In [56]:
df.isnull().sum()

PatientID     0
Name          0
Department    0
Doctor        0
BillAmount    0
dtype: int64

In [62]:
merge_df = df.merge(df2, on='PatientID')

In [63]:
merge_df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

In [66]:
Concatenate = pd.concat([df, df2])

In [67]:
Concatenate

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,NaN,NaN
1,102,Bob,Neurology,Dr. John,6233.333333,NaN,NaN
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,NaN,NaN
3,104,David,Cardiology,Dr. Smith,6200.000000,NaN,NaN
4,105,Eva,Dermatology,Dr. Rose,6233.333333,NaN,NaN
0,101,NaN,NaN,NaN,NaN,2000.0,3000.0
1,102,NaN,NaN,NaN,NaN,1500.0,3500.0
2,103,NaN,NaN,NaN,NaN,2500.0,5000.0
3,104,NaN,NaN,NaN,NaN,3000.0,3200.0
4,105,NaN,NaN,NaN,NaN,1000.0,4000.0

In [68]:
Concatenate_col= pd.concat([df, df2], axis=1)

In [69]:
Concatenate_col

,PatientID,Name,Department,Doctor,BillAmount,PatientID,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,101,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,102,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,103,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,104,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,105,1000,4000

In [70]:
merge_df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000